#!/bin/sh

set -e

if [ "$1" = "remove" ] ; then
	update-alternatives --remove jsondiff /usr/bin/python2-jsondiff
	update-alternatives --remove jsonpatch /usr/bin/python2-jsonpatch
fi


# Automatically added by dhpython:
if which pyclean >/dev/null 2>&1; then
	pyclean -p python-jsonpatch 
else
	dpkg -L python-jsonpatch | grep \.py$ | while read file
	do
		rm -f "${file}"[co] >/dev/null
  	done
fi

# End automatically added section


exit 0
